### ISSUE TITLE
Investigate CTRE driving types

### ISSUE THREAD

**Issue by NolanCampbell2357** [frc2357/FRC-2024#41]
Noticed in our drive command we are using a drive request type called OpenLoopVoltage. We should look into what other drive request types there are, and how to use them.

**Comment by Tyson453** [comment]
Notes:

- Change `Constants.PHOENIX_TUNER.STEER_CLOSED_LOOP_OUTPUT` and `Constants.PHOENIX_TUNER.DRIVE_CLOSED_LOOP_OUTPUT` from `Voltage` to `TorqueCurrentFOC`
- Use `DriveRequestType.Velocity` instead of `DriveRequestType.OpenLoopVoltage` for `CommandSwerveDrivetrain.driveRequest`
- Need to tune `Constants.PHOENIX_TUNER.STEER_GAINS` AND `Constants.PHOENIX_TUNER.DRIVE_GAINS`

@NolanCampbell2357 I believe this is all we need to do to change from open loop voltage to closed loop velocity and FOC
